@VSFrontendBackend.Server_HostAddress = https://vsfrontendbackend-backend-ggf8amawbgfub6a9.westeurope-01.azurewebsites.net // {{$processEnv SERVER_HTTP_URL}}


GET {{VSFrontendBackend.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
