@VSFrontendBackend.Server_HostAddress = https://mppbackend-bcf5czg8fffqc7ft.germanywestcentral-01.azurewebsites.net/ // {{$processEnv SERVER_HTTP_URL}}


GET {{VSFrontendBackend.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
